import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <div className="header">
            <div className="tabs">
              <button className="tab">Exchange</button>
              <button className="tab">Wallet</button>
            </div>
            <div className="tabs">
              <button className="tab">Overview</button>
              <button className="tab">Funding</button>
              <button className="tab">Spot</button>
              <button className="tab">Futures</button>
            </div>
          </div>

          <div className="value-section">
            <div className="total-value">
              <p>Est. Total Value</p>
              <h2>$0.00915855 USD</h2>
            </div>
            <div className="pnl">
              <p>Today&apos;s PNL</p>
              <span className="positive">+0.00035857 (+4.07%)</span>
            </div>
            <div className="actions">
              <button className="add-funds">Add Funds</button>
              <button className="send">Send</button>
              <button className="transfer">Transfer</button>
            </div>
          </div>

          <div className="crypto-holdings">
            <div className="crypto-item">
              <div className="crypto-name">
                <span className="icon">🪙</span> <span>HUMA</span>
              </div>
              <div className="crypto-info">
                <p>Huma Finance</p>
                <p>Amount: 0.22134242</p>
                <p>Value: $0.008457</p>
                <p className="pnl">
                  Today&apos;s PNL:{" "}
                  <span className="positive">+0.00 (+4.43%)</span>
                </p>
                <p>Average Cost: $0.06280993</p>
              </div>
            </div>

            <div className="crypto-item">
              <div className="crypto-name">
                <span className="icon">💲</span> <span>USDT</span>
              </div>
              <div className="crypto-info">
                <p>TetherUS</p>
                <p>Amount: 0.000701</p>
                <p>Value: $0.000701</p>
                <p className="pnl">
                  Today&apos;s PNL: <span className="neutral">+0.00 (+0%)</span>
                </p>
              </div>
            </div>

            <div className="crypto-item">
              <div className="crypto-name">
                <span className="icon">🎥</span> <span>BTTC</span>
              </div>
              <div className="crypto-info">
                <p>BitTorrent</p>
                <p>Amount: 0.10</p>
                <p>Value: $0.000000</p>
                <p className="pnl">
                  Today&apos;s PNL:{" "}
                  <span className="negative">+0.00 (-1.56%)</span>
                </p>
              </div>
            </div>

            <div className="crypto-item">
              <div className="crypto-name">
                <span className="icon">🌙</span> <span>LUNC</span>
              </div>
              <div className="crypto-info">
                <p>Terra classNameic</p>
                <p>Amount: 0.0000948</p>
                <p>Value: $0.00</p>
              </div>
            </div>
          </div>

          <div className="footer">
            <button className="footer-btn">Home</button>
            <button className="footer-btn">Markets</button>
            <button className="footer-btn">Trade</button>
            <button className="footer-btn">Futures</button>
            <button className="footer-btn">Assets</button>
          </div>
        </div>
      </main>
    </>
  );
}
